name: CD
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  check-compatibility:
    name: Check compatibility
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt
      - name: Set up API server
        uses: opvious/api-server-action@v0.2.0
        with:
          license-key: ${{ secrets.OPVIOUS_LICENSE_KEY }}
      - name: Check compatibility
        run: ./scripts/check-compatibility.sh
      - name: Show API logs
        if: failure()
        run: opvious api logs
  deploy-jupyterlite-site:
    name: Deploy JupyterLite site
    timeout-minutes: 3
    runs-on: ubuntu-latest
    needs: check-compatibility
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: python -m pip install -r requirements.pages.txt
      - name: Build
        run: jupyter lite build --contents resources --output-dir dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
