name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  validate-sources:
    name: Validate sources
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Validate
        uses: opvious/register-specification-action@beta
        with:
          token: ${{ secrets.OPVIOUS_BETA_TOKEN }}
          sources: sources/*.md
          dry-run: true
  deploy-jupyterlite-site:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build
        run: jupyter lite build --contents notebooks --output-dir dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
