name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  validate-sources:
    name: Validate sources
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Validate
        uses: opvious/register-specification-action@beta
        with:
          token: ${{ secrets.OPVIOUS_BETA_TOKEN }}
          sources: sources/*.md
          dry-run: true
