name: Periodic
on:
  schedule:
    - cron: '5 * * * *'
jobs:
  check-examples:
    name: Check examples
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Install Node dependencies
        run: npm i -g opvious-cli
      - name: Create bucket directory
        run: |
          bucket="$(mktemp -d)"
          sudo chown 1000:1000 "$bucket"
          echo "OPVIOUS_BUCKET=$bucket" >>"$GITHUB_ENV"
      - name: Start API server
        run: |
          opvious api start -w \
            -b "${{ env.OPVIOUS_BUCKET }}" \
            -i latest \
            -t test+examples@opvious.io=testing
        env:
          OPVIOUS_API_IMAGE_EULA: accepted
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: python -m pip install -r requirements.notebooks.txt
      - name: Validate specifications
        run: ./scripts/validate-specifications.sh
        env:
          OPVIOUS_ENDPOINT: http://localhost:8080
          OPVIOUS_TOKEN: static:testing
      - name: Show API logs
        if: failure()
        run: opvious api logs
