name: Periodic
on:
  schedule:
    - cron: '5 */3 * * *'
jobs:
  check-image-compatibility:
    name: Check server image compatibility
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Install Node dependencies
        run: npm i -g opvious-cli
      - name: Start API server
        run: opvious api start -w -t test+examples@opvious.io=testing
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt
      - name: Validate specifications
        run: ./scripts/validate-specifications.sh
        env:
          OPVIOUS_ENDPOINT: http://localhost:8080
          OPVIOUS_TOKEN: static:testing
  # check-cloud-compatibility:
  #   name: Check server image compatibility
  #   timeout-minutes: 2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out
  #       uses: actions/checkout@v3
  #     - name: Setup Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'
  #     - name: Install dependencies
  #       run: python -m pip install -r requirements.txt
  #     - name: Validate specifications
  #       run: ./scripts/validate-specifications.sh
  #       env:
  #         OPVIOUS_TOKEN: ${{ secrets.OPVIOUS_BETA_TOKEN }}
